# Site settings
title: Jiasheng Gu
SEOTitle: JIasheng Gu | Personal	Website
description: "Hey, welcome to my website!"
# SNS settings      
github_username: https://github.com/jiashenggu  

theme: jekyll-theme-slate